title: Jian Xiao's Homepage
page-top-title: Jian Xiao
top-section-bg-text: Multimodal Learning & Contrastive Learning
home-subtitle: Jian Xiao &ensp;|&ensp; Hefei University of Technology
copyright-text: '&copy; Jian Xiao 2023-2026. All Rights Reserved.'
